---
- name: Installing Filebeat
  hosts: webservers
  become: true
  tasks:

  - name: Download filebeat deb file
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.4.0-amd64.deb

  - name: Install filebeat .deb
    command: dpkg -i filebeat-7.4.0-amd64.deb

  - name: Copy/drop in filebeat.yml
    copy:
      src: /etc/ansible/filebeat-config.yml
      dest: /etc/filebeat/filebeat.yml

  - name: Enable and configure filebeat system
    command: filebeat modules enable system

  - name: First start
    command: systemctl start filebeat

  - name: Setup filebeat
    command: filebeat setup

  - name: confirm start filebeat
    command: service filebeat start